End points node js
Koliadjun/kapusta-nodejs pull request #3
Opened 2021-12-13 16:53 UTC by Mishka31

2021-12-13 17:48 UTC, Koliadjun commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать энд-поинт добавления расхода](https://trello.com/c/fM3cWRgX/56-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%8D%D0%BD%D0%B4-%D0%BF%D0%BE%D0%B8%D0%BD%D1%82-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D1%80%D0%B0%D1%81%D1%85%D0%BE%D0%B4%D0%B0)

2021-12-13 17:48 UTC, Koliadjun commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать энд-поинт добавления расхода](https://trello.com/c/fM3cWRgX/56-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%8D%D0%BD%D0%B4-%D0%BF%D0%BE%D0%B8%D0%BD%D1%82-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D1%80%D0%B0%D1%81%D1%85%D0%BE%D0%B4%D0%B0)

2021-12-13 17:48 UTC, Koliadjun commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать энд-поинт добавления расхода](https://trello.com/c/fM3cWRgX/56-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%8D%D0%BD%D0%B4-%D0%BF%D0%BE%D0%B8%D0%BD%D1%82-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D1%80%D0%B0%D1%81%D1%85%D0%BE%D0%B4%D0%B0)

2021-12-13 17:48 UTC, Koliadjun commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать энд-поинт добавления расхода](https://trello.com/c/fM3cWRgX/56-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%8D%D0%BD%D0%B4-%D0%BF%D0%BE%D0%B8%D0%BD%D1%82-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D1%80%D0%B0%D1%81%D1%85%D0%BE%D0%B4%D0%B0)

2021-12-13 17:48 UTC, Koliadjun commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать энд-поинт получения дохода](https://trello.com/c/JuFfiCGI/58-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%8D%D0%BD%D0%B4-%D0%BF%D0%BE%D0%B8%D0%BD%D1%82-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B4%D0%BE%D1%85%D0%BE%D0%B4%D0%B0)

2021-12-13 21:50 UTC, Koliadjun requested changes
Там невеликі правки поправ і змерджу. Я напишу @bogdankol, щоб він теж підігнав код під загальну структуру.

2021-12-13 21:50 UTC, Koliadjun commented on middlewares/asyncTryCatch.js
> +const asyncTryCatch = (ctrl) => {
Можна потім виправити і використати функціяю яка є в Богдана або @bogdankol використає твою.

2021-12-13 21:50 UTC, Koliadjun commented on middlewares/validation.js
> +const validation = (argSchema) => {
Пропоную назву `validationWrapper`. Для більш зрозумілого поняття що робить функція

2021-12-13 21:50 UTC, Koliadjun commented on model/transactions/income.js
> +const schema = Joi.object({
Бажано схему Joi виставити окремо в папку наприклад `validation`

2021-12-13 22:00 UTC, ghost commented on model/transactions/income.js
> +      default: '-empty-',
краще `null`

2021-12-13 22:00 UTC, ghost commented on model/transactions/income.js
> +      default: '-empty-',
краще `null`

2021-12-13 22:00 UTC, Koliadjun commented on model/transactions/income.js
> +      type: String,
тут треба подумати чи не буде в нас проблем з переведенням строки в числа. Може варто писати число одразу?

2021-12-13 23:57 UTC, Mishka31 reviewed
Звірив, виправив

2021-12-14 14:38 UTC, Koliadjun approved these changes

2021-12-14 14:39 UTC, merged